# Generated by Django 5.0.2 on 2024-02-28 02:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIMembership',
            fields=[
                ('identifier', models.UUIDField(default=uuid.UUID('5fd8969a-789b-4b6b-ab43-c40ee25a6721'), editable=False, primary_key=True, serialize=False)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('tokens', models.IntegerField(default=10)),
                ('expiry', models.DateTimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
