# Generated by Django 5.0.2 on 2024-02-28 17:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apimembership',
            name='expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apimembership',
            name='identifier',
            field=models.UUIDField(default=uuid.UUID('7ea875fe-4219-4a7e-a435-407488d75477'), editable=False, primary_key=True, serialize=False),
        ),
    ]
