# Generated by Django 5.0.2 on 2024-02-28 18:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_apimembership_expiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apimembership',
            name='identifier',
            field=models.UUIDField(default=uuid.UUID('1e2dd5c4-0bfb-480f-af21-ae032fdee2c4'), editable=False, primary_key=True, serialize=False),
        ),
    ]
